---
title: "Part 4: The Smokies to Hot Springs (Days 11-16)"
output:
  html_document:
    toc: true
    toc_float: true
---

## Part 4: The Smokies to Hot Springs (Days 11-16)

Originally posted on June 16th, 2014 2:10pm

Day 11: Fontana Dam Shelter –> Russell Field Shelter (13.8 miles)
Day 12: Russell Field Shelter –> Mt. Collins Shelter (22.7 miles)
Day 13: Mt. Collins Shelter –> Tri-Corner Knob Shelter (20.1 miles)
Day 14: Tri-Corner Knob Shelter –> Standing Bear Hostel, with side trip to Mt. Cammerer Fire Tower (18.1 miles on AT, 1.2 mile side trip)
Day 15: Standing Bear Hostel –> Walnut Mountain Shelter (20.3 miles)
Day 16: Walnut Mtn Shelter –> Hot Springs, NC (13.1 miles)

Miles from Springer: 273.9

So I was going to enter the legendary Great Smoky Mountains. I had heard they were amazingly beautiful and eerie, but most of all, crowded. 

According to my guide book, the Smokies are the most visited of the traditional national parks. It is also home to 400-600 black bears. The combination of heavy visitation, much of it by people who don’t follow the “leave no trace” methodology of backpacking, and a large population of bears leads to unfavorable human-bear interactions. Irresponsible people feed the bears, who then get habituated to people and start to associate tents, packs and people with food. This can result in a bear who is dangerous because it begins to view humans as a food source.

With all of this on my mind, I went to sleep in the Fontana Dam Shelter. Only to be awoken at 1:30am by an elderly British woman coming into the shelter saying that a bear had just torn apart her campsite. 

Since it was the middle of the night, no one really reacted that strongly. It all seemed a little bit far fetched in the haze of sleep. She didn’t have a sleeping bag or a sleeping pad, so Hope gave her a sleeping pad and the woman slept in her clothes. We all went back to sleep.

However, in the morning, it got a lot more real. The woman pulled her tent out of her pack. It was torn to shreds. So now we listened intently as she recounted her story.

She had been set up at a campsite 5.6 miles into the Smokies. Signs were posted that warned that bears were reported to be active in that area. She was too tired to go to the next shelter, 5 miles further, so she set up her tent with her sleeping bag and pad inside. 

She was cooking her dinner away from her tent so the smell wouldn’t be associated with her sleeping area when a bear showed up.

She yelled at him to go away. He didn’t. Someone had told her once that barking like a dog would make a bear go away. So she barked. The bear didn’t even bat an eye.

She thought maybe it wanted her food. She put her food bag into her pack and walked away to go hang it, thinking the bear would just go after the food bag. As soon as she walked away, the bear started ripping apart her tent and sleeping bag. She told us that he was covered in white down feathers. At one point, he knocked away one of her hiking boots.

She went back to the campsite, and gathered everything up into a garbage bag (which she later admitted was a foolish thing to do, as the bear was still nearby). She then proceeded to walk the almost 6 miles back to Fontana Dam, in one hiking boot and one camp shoe, in the middle of a thunderstorm, in the dark.

And to top it all off, she’s 70 years old.

Needless to say, after hearing that story, I wanted to have a buddy in the Smokies. Since dogs aren’t allowed I the Park, Hope was hitching around them with her dog, King Nickie. That meant that Monk, the recently retired Navy engineer, also needed a hiking buddy. We decided to stick together.

It started raining as soon as we left the Fontana Hilton. I tried out my poncho, which worked well, but makes me look like a hunchbacked goober. The Smokies were, for lack of a more perfect word, smoky. Mist curled around all of the trees and up the mountain sides as we climbed upwards.

We had planned on staying at Spence Field Shelter, about 16 miles into the Park, but heard through word of mouth that it was closed due to bear activity. No way were we going to stay there! Instead, we stayed at Russell Field Shelter. We had heard the climb into the Smokies was going to be brutal, but honestly, it wasn’t too bad. But maybe that’s just because I like uphill better!

It poured and thunderstormed throughout the night. Monk had to make it to Mt. Collins shelter the next day, because his friend was bringing him a resupply. Since we had had a shorter day than expected, that meant that the hike to Mt. Collins was going to be a long one. I wasn’t ready to be in the Smokies alone, so I told Monk I’d head there too.

He set out before me, because he hikes slower than I do and so wanted to leave more time for the trip. It drizzled as I left camp. The trail was incredibly rutted because of the constant foot traffic. It was also overgrown by long grasses that soaked my shoes as soon as I started hiking. Great, wet socks.

The day was one huge continuous climb towards the the highest point on the AT, Clingman’s Dome at 6,643 feet. All day I could tell I was in a place where there were probably spectacular views, if it were clear. However, all I saw through the rain was a white wall of smoke.

But, it was the first day that I truly felt like a thru-hiker. You can drive almost to the top of Clingman’s Dome and walk 0.2 miles from the parking lot to the observation tower. As I was coming out of the woods, dripping and stinky in my hiking clothes, I came across an Indian man and his four children. He was wearing khakis and a polo. He was holding a large camera.

“Did you walk here?” He asked in heavily accented English, looking at my trekking poles and backpack.

I smiled and nodded, “Yeah! From about 18 miles back that way,” I pointed south.

His jaw dropped. “Just today? Did you start today?”

“Nah, I actually started in Georgia.”

“Georgia?!” His eyes grew huge, and he slapped a hand to his forehead. “I live in Georgia!”

He then started shouting for his family. Relatives seemed to appear out of nowhere, all coming to see the girl who was a “walker.” They were all dressed nicely; some of the women wore traditional Indian clothing and bindis on their foreheads.

He had all of his kids and some of the relatives crowd around me. “I have to take your picture! Stand by her.” And then, almost as an afterthought, “Can I take your picture?”

“Sure, sure,” I nodded, all the while feeling even dirtier than usual as I caught whiffs of the laundry-fresh scent wafting from their clothes.

He snapped a few pictures, then asked me how far I was going.

“As far north as I can get, hopefully Maine.”

“To Tennessee?!”

“Actually, to Maine.”

“Past Tennessee?!” His eyes widened.

“Yeah, past Tennessee to Maine.”

“Past Tennessee?!” He was stuck on that, as if he couldn’t imagine anyone ever walking further than Tennessee.

I laughed and nodded. I told him I had to keep going, but as I walked away he told me, “I’m proud to have taken your picture.” It was a surreal and incredibly nice moment for me. He definitely made me feel like I was doing something special.

After that, even the ugly concrete observation tower on top of Clingman’s, the hordes of people on it, and the complete and utter lack of views there couldn’t put a damper on my spirits. I floated the last 4 miles into Mt. Collins shelter.

Just as I arrived at the shelter, another storm hit. It started pouring. I thought that Monk would already be there, because I hadn’t seen him all day and hadn’t thought that I’d passed him. But he wasn’t there. Uh oh, I thought. He’s still out there. The rain was beating down on the tin roof of the shelter. 

There were four guys at the shelter. A father and his young son, an older man, and a guy about my age. As soon as I walked up, they asked how far I’d come. When I told them, the guy my age said I must be like Sonic the Hedgehog to walk so far and come into camp by 5pm. He pointed at my dirty calves and said, “You can tell how fast she walks by the mud splatters on the backs of her legs!” I had gotten my trail name.

We had a great time hanging out, talking about everything from moonshine to salamander regeneration. 

(This is a super cool topic. A salamander can regenerate any body part from any non-fatal wound. The dad of the father-son pair was researching this. He knew everything about salamanders. He walked out into the storm a couple times, turned over logs, and brought back different salamanders for me to look at. He showed me the red-cheeked salamander, which is only found in the Smokies, and the two-line salamander. He also identified the bright orange one I took pictures of. It’s a poisonous newt apparently!)

However, the whole time I was getting concerned about Monk. The rain continued, and on occasion, turned to hail. I hoped he had holed up somewhere to wait out the storm. But no cigar. A couple hours later, Monk came in, drenched to the bone. We helped him get into relatively dry clothes and make some food. But it seemed like our time hiking together was done for the moment. After getting his resupply from his friend, he had to go into Gatlinburg the next day to get dried out.

We parted ways and I headed to Tri-Corner. It was a relatively easy section, mostly gently rolling. I was walking along a knife-edge ridge most of the day. The path was only 20 feet wide at some points, sheer drop offs on either side. I also finally saw the shimmer of blue sky. 

But alas, because it was the Smokies, it couldn’t last. Right around 2pm, I heard thunder start to threaten. Then, at 2:30pm, it paid off on its threat. It started to pour. The trail turned into a water funnel, running better than most of the “streams” in Georgia. I donned my poncho and got a move on. I wanted off that ridge. I had a single layer of trees on either side, so I wasn’t completely exposed, but I didn’t like the thought of there being lightning while I was holding two metal rods in my hands.

I booked it to the shelter. I was wet, but dried off soon enough. I spent the night in the shelter with a nice group of people on an REI adventure trip.

I decided to high-tail it out of the Smokies the next day. We weren’t getting along. I had been told by many people to do the Mt. Cammerer side trail because there were amazing 360 degree views from the lookout there. Of course, when I got there, there was nothing but that same old wall of white mist. Great.

I scooted down the trail towards the Standing Bear Hostel. As soon as I was out of the Smokies, everything took a turn for the better. The sun came out. I hiked along a beautiful creek. The trail was smooth and dry. I was happy to be out of the park. I got to the hostel, drank a beer, and met some fellow hikers. It was relaxing and fun.

The next morning I started the section of trail that follows along the North Carolina-Tennessee border. It was gorgeous. I thought the day highlight would be when I crested the bald summit of Snowbird Mountain, but then I came to Max Patch. And holy shit. It was far and away the best view yet.

A huge grassy knoll with sweeping 360 degree views of mountains that seemed to go on for forever into the distance. The sun beat down pleasantly on my back. I was out of the green tunnel. I walked around with a huge smile on my face, my head on a swivel as I tried to see everything all at once. It was the first place that I’ve felt like I need to go back to.

I moved on somewhat reluctantly. I passed some other thru-hikers and stopped for lunch at Roaring Fork Shelter. I decided to press on, after talking it through with an older man there. As I left, he told me I looked about 14, but that I also looked like I had my “shit figured out.” That made me laugh.

I climbed an easy 5 miles up to Walnut Mountain Shelter where I met a college aged couple. I felt like I could’ve kept hiking, but I was having too much fun talking to people my own age to leave. As we ate dinner, another pair of recent college graduates showed up at the shelter. We all made plans to meet in Hot Springs the next day to eat real food and drink some beer.

I left early the next morning so that I’d have time to run errands in town. The hike down was a breeze. I walked through many rhododendron tunnels where the sun was almost completely blocked out inside. It also got progressively warmer and drier as I dropped down in elevation towards Hot Springs.

The trail runs right through Hot Springs, so once I was in town, I stopped for lunch. I ate a huge meal of chicken and mashed potatoes smothered in gravy with kale salad and a Pepsi at the Smoky Mountain Diner then checked in at the historic Sunnybank Inn. 

Now I’m running errands, resupplying on food and doing laundry. A nice half day before the next section of trail. Hopefully it stays smooth and rolling like this last section. I think that the bit between Standing Bear and Hot Springs has been my favorite section so far.

