---
title: "Part 2: Days 5-8"
output:
  html_document:
    toc: true
    toc_float: true
---

## Part 2: Days 5-8

Originally posted on June 9th, 2014 8:23am

Day 5: Dicks Creek Gap/Top of Georgia hostel –> Muskrat Creek Shelter (11.8 miles)
Day 6: Muskrat Creek Shelter –> Long Branch Shelter (21.1 miles)
Day 7: Long Branch Shelter –> Winding Stair Gap/Franklin –> Wayah Shelter (18.3 miles)
Day 8: Wayah Shelter –> Nantahala Outdoor Center (16.3 miles)

Miles from Springer: 137.1

I’ve hit some of my first big milestones since I last posted: first state line (GA/NC), first 100 miles, first thunderstorm. 

The day after I posted I headed out with the guys I met at the first hostel I stayed at (Eric, Alex, and Craig) along with a goofy guy named Chris who we met at the Top of Georgia hostel. We almost missed the unassuming state border sign, but got lucky and stopped to take pictures with it. 

We had heard North Carolina was going to be a lot tougher than Georgia. For the most part, they seem to be pretty much the same, except that North Carolina likes to climb mountains really steeply and quickly, whereas Georgia does it over long drawn-out miles. 

We didn’t want to push ourselves too far, so we stopped after a relatively short day. My knees were happy about that.

My tent was tested in its first rainstorm that night, and it performed great. I woke up dry and ready to hike. We split off from Chris and set off on another relatively gentle hike. The trail was pretty smooth, the sun was shining and it wasn’t too hot. A great day. Since we weren’t too tired, we decided to push on over Albert Mountain to reach the Long Branch Shelter. Despite thunder threatening, we climbed the metal observation tower and got our first 360 degree view. It was amazing to finally get above all of the trees and get a sweeping view of the rolling mountains. In the distance we could see the faint shimmer of water, Fontana Dam, the last stop before the Great Smoky Mountains. Dark clouds overhead kept us from staying longer to celebrate our first 100 miles from Springer Mountain.

We tried to sleep in the shelter, but the squeaking of mice sent me running to set my tent up outside. I wasn’t about to have little rodents sharing my sleeping bag! The boys set up their tents inside the shelter which was a funny sight. 

Although I don’t have a trail name yet, I have taken to calling the boys “The Plague”, because their group seems to be dropping off the trail like flies.

Trail names are kind of a rite of passage out here. Most people’s names are given to them by other hikers. Many names are based on food, which is a big topic of conversation out here. I’ve heard of a “Ramen Shamen” and a “Maple Syrup”. But the names aren’t always what you want them to be, particularly if you do something memorable. For example, I heard that one guy who consistently passed a lot of gas at the shelters is now referred to as “Chevron”. I hope I don’t get stuck with one like that!

The next morning we pushed on 8 miles to Winding Stair gap, where we hitched a ride into Franklin to resupply. It was my first time hitchhiking, and I have to say, it was easier than I thought it would be! No more than 5 cars passed us by before Eric and I were picked up by a man with the thickest Southern accent I’ve ever heard. He told us he picked up hikers all the time and had always dreamed of hiking the AT himself. He dropped us off at WalMart, where we waited about 20 minutes for Craig and Alex. They didn’t have as good of luck getting a ride. I think it might help that I’m a girl…

After picking up about 12 candy bars each,  we went across the street to an all you can eat (AYCE) Chinese buffet for lunch. We  stuffed ourselves. I don’t think I’ve ever eaten so much in one sitting.

After that, the boys were too full to think about hiking. They wanted to hitch another ride to the center of town so that they could get a beer. I wanted to keep hiking with them, but I also wanted to get back on the trail. I knew I could get in at least a few more miles if I   went back sooner rather than later. I didn’t want to get stuck staying the night in Franklin. And honestly, all of the cars and people in town were a little off-putting after so many days of quiet and relative solitude. 

So we said our goodbyes and went our separate ways. I ended up taking a taxi back to the trail. Although it had been  thrilling to hitch with the Plague, the prospect of doing it by myself was a little daunting. I hiked right up until dusk and had just finished pitching my tent and hanging my food when full dark arrived.

Around 2am, I woke up to the sound of rain. I wasn’t too worried though, because my tent had done so well earlier that week. Then it started thundering. Not gentle thunder that you can tell is far away, but bone rattling thunder that lasted for minutes on end. There was no start and stop, every time it seemed to die down, the thunder seemed to amp itself back up and crack to a new level of loud. 

Then the lightning started. It was like a strobe light outside of my tent. I lay awake, glad that I wasn’t on an exposed ridge, but still worried about the potential for trees to blow down. I tried doing the trick where you count the time between the thunder and lightning to see how far away the storm is, but since they were simultaneous, I figured I was in the heart of it.

The rain started beating down on my tent so hard that a fine mist sprayed down on me after every drop. I turned on my headlamp and realized I was laying in a small puddle of water. At this point, I decided that it would be better to deal with a few mice than a completely soaked bag. Even though the storm had only died down a little bit, I bundled all of my stuff under my arms and made a mad dash to the shelter. I ran back and took down my tent also. I spread everything out to dry in the shelter and spent a long night keeping warm by walking around and watching the lightning from the shelter.

The next morning, I dried everything off as best as I could, packed up my bag and headed out. Luckily, the rain had stopped and the sun was shining through mist rolling off the mountains. The plan was to get to the Nantahala Outdoor Center (NOC), where I could sleep in a bed and take a shower. And hot damn did that sound good. 

The day started out similarly to how North Carolina had been the last few days. But then she showed her true colors. The day ended with a brutal 6 mile, 2,400 ft descent that seemed to last for years. My knees hurt every step of the way. And it wasn’t always a nicely graded descent either. At points, I was scrambling down from huge rock to huge rock.

But I made it and took one of the best showers of my life. I took a nap and then walked around the NOC like a scrub in my Crocs and dirty clothes. But I didn’t care, because I got myself a pulled pork sandwich and a beer and life was just dandy.

Today, I ate breakfast at the restaurant, bought some more supplies, and watched the many tourists head out on whitewater rafting trips the NOC is known for. I’m feeling well rested and ready for the apparently equally brutal climb out of the NOC. From here, the next stop is Fontana Dam and then on to the Smokies.

