---
title: "Part 5: Hot Springs, NC to Damascus, VA"
output:
  html_document:
    toc: true
    toc_float: true
---

## Part 5: Hot Springs, NC to Damascus, VA

Originally posted on June 26th, 2014 1:34pm

Day 17: Hot Springs –> Little Laurel Shelter (19.6)
Day 18: Little Laurel Shelter –> Hogback Ridge Shelter (20.2)
Day 19: Hogback Ridge Shelter –> Erwin, TN/Uncle Johnny’s Hostel (27)
Day 20: Erwin, TN –> Deep Gap (12.1)
Day 21: Deep Gap –> Greasy Creek Gap/Greasy Creek Friendly (12.1)
Day 22: Greasy Creek Gap –> Overmountain Shelter (16.9)
Day 23: Overmountain Shelter –> Moreland Gap Shelter (27.6)
Day 24: Moreland Gap Shelter –> Wilbur Dam Rd –> Black Bear Resort (19.1)
Day 25: Black Bear Resort –> Wilbur Dam Rd –> Abingdon Gap Shelter (27.4)
Day 26: Abingdon Gap Shelter –> Damascus –> ? (10+?)

So, it’s been a little bit since I last wrote and a lot has happened. The trail and Mother Nature like to prove me wrong whenever I start thinking I’ve got this thing figured out and that it might be getting boring. Let me tell you, as soon as that thought crosses your mind, things get real interesting. Without further ado, here’s my journey from Hot Springs, NC to Damascus, VA.

I left Hot Springs after eating an organic vegetarian breakfast at Elmer’s (the Sunnybank Inn). I headed out with another thru-hiking girl who had just finished undergrad. We talked about the trail and our experiences so far. We soon went our separate ways, but it was fun to meet another solo woman thru-hiker. We’re a bit of a rare breed.

And that’s actually one of the interesting things I’ve noticed on the trail–the way the conversation heads depending on whether I’m talking to a guy or a woman. Guys, the first thing they want to talk about is gear and how I got my pack so damn light. Women want to talk about what it’s like being a woman on the trail. Both conversations are good ones, but the divide is certainly clear.

The hike up from Hot Springs wasn’t too bad, but it was certainly HOT. I was pouring sweat on the uphills, and then it would get dry on the downhills and I would feel crusty from the salt. I started realizing I was going to have to seriously increase my water and electrolyte intake.

When I got to the Little Laurel Shelter, I was excited to see that I’d caught back up with Hope and King Nickie. They’d shuttled around the Smokies, because dogs aren’t allowed in the park. It was great to catch up with her and talk about how we’d been doing since we split ways at the Fontana Hilton.

We said our goodbyes the next morning and I headed out without much plan for where I would stay. It was another pretty hot day and I spent most of the day drenched in sweat. I stopped for lunch at Flint Mtn Shelter, where I ate with another thru-hiker named Bach (for the composer he plays most often on the guitar he carries). 

I was just about to leave the shelter when another couple walked up. They noticed that my hat says “Surf Cup Soccer a Tournament”, and so we got to talking soccer. By random chance, I mentioned that I’d played at Whitman. The woman, Gizelle, then said that might mean I knew Jesse Mirman. My jaw dropped. We had been housemates for the last year! What a crazy small world we live in. We talked for a while about how they had gone to the same schools growing up and how she was friends with his brother. It was an unexpected and fun conversation.

We went our separate ways, and I pressed on towards the next shelter. It was a longer and harder walk than I was expecting based on the elevation profiles in my book. I got to the shelter feeling worn out and beat. I met an older guy named 50+ (for his age and pack weight) there. Bach was also staying there. We hung out and chatted trail, but I went to sleep early. I fell asleep to the talented strumming of Bach’s guitar.

I woke up the next morning feeling strangely refreshed, even though it was only 6:45am when I left camp! I hadn’t planned on walking far, but I looked at my book and realized that Erwin (and a hostel with showers and real food!) was 27 miles away. It would be a push…I set my mind on staying at the shelter before Erwin.

The morning passed by quickly as I climbed up to Big Bald. It was amazing to be on top of the open mountain and to watch the weather change before my eyes. Fog blew quickly across the hill giving it an eerie appearance. Ravens and other birds flapped out of trees as I scared them out of their roosts.

At one point, I stopped and looked to the right. For one perfect moment, I saw a huge wild turkey nestled in the tall grass next to the trail, a tiny chick tucked under a wing. I saw her mottled brown and white feathers. I was just getting over the initial shock of seeing such an amazing thing when she got spooked and spread her wings wide only a foot from my face and flew away, squawking. The chick went tumbling into the grass. I jumped back in surprise, then walked away, calling out to the turkey to go back and get her baby.

I pressed on and made it to the shelter before Erwin by 2:30pm. From there it would only be 6.5 miles to a shower….it was too tempting not to hike onwards. I ate a quick lunch and was back on the trail by 3pm. It was a hard, hot walk down to the Nolichucky River. Thunder was constantly threatening overhead and wind was whipping through the trees. That is usually a recipe for rain out here. I wanted to make it to the hostel by 5pm, because I heard they had a dinner shuttle. I wanted that dinner!

I boogied down the trail and made it to Uncle Johnny’s at 5:05pm, convinced the shuttle had already left but happy that it hadn’t rained. When I paid for a bunk, the guy told me it was my lucky day. The shuttle was running late and I’d not only get to go into town to eat, I’d also get to shower first! Clutch.

I ate some so-so Mexican food and drank a margarita. I think the Taqueria in Walla Walla spoiled me. I still wolfed down every bite though. The hiker hunger has hit me–I’m hungry. All. The. Time. I eat, I’m hungry. I go to sleep, I’m hungry. I wake up, I’m hungry. It’s unreal the amount of food I can pack away.

I hung out in the bunkhouse with a funny guy named Roger Rabbit. I had planned on leaving early the next morning, but I heard there was a lunch shuttle at 11:30am to an AYCE pizza and salad buffet. Now usually I’m not a big cheese eater, but I’d actually been dreaming about pizza. No way was I passing that up.

I gorged myself on pizza. Two loaded plates of pizza and two equally loaded plates of salad later, I waddled over to the IGA grocery store to resupply. I bought several days worth of food, got the shuttle back into town, then hit the trail, even though dark clouds were building overhead.

At first, it was just as hot and sweaty a climb out as it had been since Hot Springs. Then the wether changed. The wind started shaking the trees and pushing me sideways. Worried about the weather, I practically ran through an open field called Beauty Spot. Just as I passed through it, the rain started. It rained like it has building itself up for weeks. I poncho’d up and headed for Deep Gap. I didn’t hike very far because I’d started so late, but I was happy to get there and get my tent set up. I hunkered down, feeling safe and dry in my tent.

The shelters have made me lazy. When you wake up, there’s no tent to take down and nothing is wet. When I woke up at Deep Gap, my tent had done well at keeping everything inside it dry, but I still had to shake out and wipe down the tent. I got everything packed up as it drizzled. As I started walking, it started pouring. Really deluging. The fog was so thick I could hardly see 20 feet in front of me.

The trail became slick. My feet slipped backwards on every step uphill. On the downhills, I’d start sliding around like I was mud surfing.  Sounds like it might be fun, but it was anything but. A couple of times I’d slip on the downhill fast enough that I’d lose my balance, my arms would start flailing and I’d end up falling on my butt. Luckily, I never hurt myself, but I was muddy and dirty and frustrated. Not efficient or fun hiking weather.

When I got to the Cherry Gap Shelter, I noticed some graffiti scrawled on it that said:

“To be a thru-hiker, you must:
1. Summit katahdin
2. Summit springer
3. Stay at the Greasy Creek Friendly!!!”

That was the third endorsement of the place that I’d heard. I made the decision to walk the 0.6 miles off the trail to go to it. I was not having a good day and so there was no point in hiking further. I followed arrows made out of sticks and rocks down an old jeep track to the house. Painted on the door was a yellow smilie face. I was already starting to feel like I’d made the right decision.

I knocked on the door and the woman, Connie, immediately came out and helped me wash my muddy legs and poncho. She hung the poncho for me and showed me where the shower was. After I was done, I changed into a pair of sweatpants and a t-shirt that were at least 3 sizes to big. Connie fed me lentil soup, pineapple and cantaloupe, then set me up on the couch with a huge stack of movies that I could choose from. I sat and watched three movies.

It was exactly what I needed. And Connie was the best. All of the endorsements had it right on the money. It was truly like being at a home away from home, like I was visiting  a relative or something. She totally turned my day around. I went to sleep feeling rejuvenated and relaxed.

The next day Connie made me scrambled eggs and my first ever grits (learned they’re not for me), and then I set out in freshly laundered clothes on a clear day. I had a nice day with many views from a series of balds. I even got my first sunburn of the trail! I made it to the awesome and highly recommended Overmountain Shelter. It was a huge red barn that had been converted into an AT shelter. It had amazing views of the valley below.

I met two women and two men there, all of whom were very nice. It was great talking with all of them. I woke surprisingly early the next morning and headed out with some pep in my step. Unfortunately it was very foggy, so I didn’t get any views from Hump Mountain, but I did see the elusive Gray’s lily. according to my book, it’s a protected red lily that only blooms in June-early July.

I officially hiked out of North Carolina after the long section of trail that had straddled the NC-TN since the Smokies. I made it to the Mountaineer Falls Shelter 18 miles from where I’d started and thought I might end my day there, even though it was only 2pm. 

But then Mitch showed up. This take a bit of explaining, so stay with me for a second here. In all of the shelters, there’s log books where hikers can jot down their experiences from the day, poems, drawings, future plans, basically anything they want. As a game, I would pick out people and follow their progress along the trail ahead of me. Occasionally, I’d pick someone out and try to catch them.

I had first heard about Mitch before Fontana Dam, so I’d been chasing him for a long time. People I passed along the trail would mention him and tell me tidbits they’d learned about him. So even though we’d never met, I knew he wore an orange long-sleeved shirt and was a tall, skinny dude a little younger than me. I had slowly been gaining on him, and in fact missed him by an hour at the Greasy Creek Friendly.

So when a tall guy dressed in an orange shirt rolled into the shelter, I knew it was Mitch. He said he was going onto the next shelter, and even though I was tired, I was too excited to stay behind. It was fun to hike with someone who walked just as fast (if not faster–he’s got a lot longer legs than I do!) as I do. I don’t usually get to hike with people, so it was a nice change.

We got to the shelter and I saw that he had a whole different level of hiker hunger. He ate for like an hour and a half straight. He eats around 6,000 calories a day and is just barely maintaining his weight.

We made plans to push onto Vandenventer Shelter the next day, 24 miles from where we were, because there was an area that was closed due to bear activity that we’d have to hike past. I left early in the morning so I could pop off trail and resupply at the Black Bear Resort, which was 7 miles from where we had stayed the night.

I met some nice people when I resupplied, but then I pressed on, never expecting to see them again. I hiked all day, and it was another hot one. On my way up a mountain, I heard rustling to my right and saw a bear. Before I could even make some noise, it scampered off into the woods. It seemed like a pretty tame first bear sighting, but at least I’d finally seen one! 

I dropped down to Watauga Lake, which has a sandy beach that was covered in people swimming. I passed the lake and followed the trail along the shore in the area with active bears. 

And I could see why it would be a serious bear-itorry. Trash was strewn everywhere. It was clear that since it was easily accessible that people who weren’t conscious of their impact would party or picnic along the shore and leave their mess. No wonder there were problem bears–trash and leftover human food is a much better source of calories than grubs and berries that haven’t even come into season yet.

I pushed myself hard to get out of that area as quickly as possible. I didn’t like the idea of bears who were so habituated to people that they weren’t scared of us anymore. I walked over the Watagua Dam, which was pretty cool, but kept on walking until I was out of the restricted area when I crossed Wilbur Dam Road. Even though I knew it was a purely arbitrary line drawn by humans, I still relaxed a little bit and felt like I was in the clear. I was now only 5 miles from the Vandenventer shelter.

As I hiked up switchbacks that lazily headed east up the mountain, I came across a pile of bear scat. This wasn’t unusual, except for the fact that it was still light brown and wet looking, instead of black and dried out like most piles I’d seen. In fact, flies were hovering all around it. Weird, I thought, but continued upwards.

I turned around the next corner and boom. I saw a bear about 20 feet from me. And not a little one either. I made some noise and clicked my poles together. She didn’t move a muscle, just stared at me. Then I heard some rustling down below me. Cubs?

I thought maybe that was why she was standing her ground, to protect her cubs. So I backed away and walked a ways back down trail, talking loudly all the while. I figured that if I left and she knew I was away from her, that she would skedaddle with the cubs as soon as I was a safe distance away. I made loud noises for five minutes, then figured she’d have to be gone. I walked back up.

I turned the corner again, and there she was. In the exact same spot. I spoke loudly at her, she just looked at me. I clacked my poles, she just looked at me. I put some heat in my voice and told her to go away.

She immediately stomped her paw down on the ground and snorted and huffed loudly out of her nose. That is the sign of an aggressive bear, and I knew it was time for me to get out of there. She was not reacting like a normal bear. This might be the problem bear, who had completely lost its fear of humans.

I backed away and then hightailed it back to the Wilbur Dam Road. I called my mom, who rightfully so, freaked a little bit. At this point, I was tired, dehydrated and a little bit freaked myself. Going forward by myself wasn’t smart because of the bear. Going backward would put me in the restricted area. We couldn’t figure out what to do.

Eventually we decided that I should walk down Wilbur Dam road towards a visitor center listed in my book. But as I walked down the road, it looked less and less like there would be anything there. And huge black clouds were gathering overhead.

So I flagged down the next car that drove by. It ended up being an amazing nice woman and her daughter, who was about my age. They listened to my story and then told me they’d drive me to a hostel, even though I’m pretty sure it was entirely out of their way. I made friends with their kitten in the backseat and they took me to McDonalds for some food. We ended up turned around so much that they actually took me all the way back to the Black Bear Resort. I took a shower and hung out and watched movies with a guy I had met earlier that morning. Another much needed relaxation time after an incident that shook me a little bit.

The next morning, they shuttled me back to the Wilbur Dam Road and I sprinted past the section where I’d seen the bear. I whistled terribly and sang off-key all day, just so there wouldn’t be anymore surprise encounters. It rained and rained. I caught Mitch again at a shelter in the middle of the day. We made plans to meet two shelters down the trail at Abingdon Shelter. The last bit of Tennessee was easy and relatively flat. A lovely little walk.

That night at the shelter, I set up Mitch’s mousetraps. The mice there were incredibly bold and ran around even while we were up and walking around. But not fifteen minutes after we put the traps out, we heard a big crash. Two mice had fallen from the rafters. One was stunned by the trap, his face a little crushed. The other scampered away. Mitch grabbed a shovel left at the shelter and killed it. He threw its body into the woods. Ten minutes later, another crash. This mouse was pinned by the trap but still alive. These traps were not working great…Mitch killed that one too, but blood was all over the trap. He didn’t want to pack out the bloody trap, so I dug a hole to bury the mouse and trap in. It was certainly an interesting night.

Today, we made it into Virginia and Damascus. First big landmark! Great feeling. Mitch’s parents also randomly happened to be in town, so we hung out with them and resupplied. I was lucky enough to have a package from my parents and new shoes. Yay for traction and no holes!

Until next time!

