---
title: "Part 6: Damascus, VA to Waynesboro, VA"
output:
  html_document:
    toc: true
    toc_float: true
---

## Part 6: Damascus, VA to Waynesboro, VA

Originally posted on July 15th, 2014 5:21pm

Day 26 (part 2): Damascus –> Saunders Shelter (9.4 miles)
Day 27: Saunders Shelter –> Old Orchard Shelter (29.6 miles)
Day 28: Old Orchard Shelter –> Va. 16, Mt. Rogers NRA Headquarters –>  Marion, VA/Travel Inn (24.8 miles)
Day 29: Marion, VA –> Va. 683/Relax Inn (11.5 miles)
Day 30: Va. 683 –> Chestnut Knob Shelter (23 miles)
Day 31: Chestnut Knob Shelter –> Helveys Mill Shelter (24 miles)
Day 32: Helveys Mill Shelter –> Woodshole Hostel (31.2 miles + 0.6 mile side trip + 0.5 miles to hostel)
Day 33: Woodshole Hostel –> Pearisburg, VA/Holiday Motor Lodge (10.4 miles)
Day 34: Pearisburg, VA –> Bailey Gap Shelter (23.2 miles)
Day 35: Bailey Gap Shelter –> Niday Shelter (27 miles)
Day 36: Niday Shelter –> Va. 311 –> Julie –> Sam and Sara’s (22.7 miles)
Day 37: Sam and Sara’s –> Va. 311 –> Daleville, VA –> Hiker Mom’s (19.8 miles)
Day 38: Hiker Mom’s –> Daleville, VA –> Wilson Creek Shelter (11.2 miles)
Day 39: Wilson Creek Shelter –> Bryant Ridge Shelter (20.8 miles)
Day 40: Bryant Ridge Shelter –> Matts Creek Shelter (22.6 miles + 2.2 mile side trip)
Day 41: Matts Creek Shelter –> US 501 –> Glasgow, VA (2.2 miles)
Day 42: Glasgow, VA –> US 501 –> Pedlar River Bridge (15.1 miles)
Day 43: Pedlar River Bridge –> 3 Springs Hostel (where I got to watch the World Cup Final, awesome!) –> Seeley-Woodworth Shelter (20.7 miles)
Day 44: Seeley-Woodworth Shelter –> Maupin Field Shelter (20.4 miles)
Day 45: Maupin Field Shelter –> Rockfish Gap –> Waynesboro, VA (20.8 miles)
Miles from Springer: 857.8
Just before I got out of the van, the man who was dropping me off at the approach trail turned to me and said,
“You won’t believe me now, but at some point, you’re going to get bored of hiking.”
He was right on both accounts.
In that moment, full of adrenaline and fear and excitement for what was to come, I couldn’t imagine not loving every step I took…Or at least the fact that I was getting to take those steps. I’ve always known that sometimes hiking is hard and painful, but in the end, the satisfaction that I would get from successfully doing that hard and painful thing always made it worth it. It was preposterous that I could get bored of hiking. Not when there were mountains to climb, bears to meet, and streams to jump!
But now, I see what he meant.
See, it’s not that I want to or that I have even considered getting off the trail. That’s not it at all. I think it’s just what happens when you do anything day after day after day: at some point, the extraordinary becomes mundane. What was foreign becomes familiar. I think I’ve made the transition from this being a “trip” to this just being the way I’m living right now. It’s gotten to the point where I can hardly remember a time when I wasn’t doing this.
I wake up. I walk until dark. I sleep. That is my entire day. Every day.
Yes, of course, more happens than that. And yes, of course, there’s some variation in the events of the day, like the terrain or the scenery. But when you boil it down to its essence, that’s all I’m doing.
Wake up. Walk. Sleep. Rinse and repeat.
I used to judge people who listened to music or podcasts while hiking. I thought it took them away from the experience. What good was being away from civilization if you brought technology right back into it? What good was being in nature if you wouldn’t even listen to the birds singing? You might as well be working out in a gym.
But now, I understand.
Now, I use my music as a tool. It gives me an escape from the relentless sameness of it all—another dusty ridge to traverse, another rat snake to avoid, another pile of rocks to scramble over. It gives me solace when I pant my way up another boulder-strewn mountain, only to reach yet another viewless, tree-covered summit. It gives me peace when the same thoughts bounce endlessly against the same corners of my brain. It brings new life to an overlook that gives me yet another view of perfectly sculpted green hills rolling on forever into the northeastern distance.
However, I wouldn’t still be doing this thing if it always felt like that. There have been moments of wonder and joy and awe. When I sat on the rock outcropping at McAffee Knob, I felt like I was dangling my feet over the end of the world. When I dove into the James River and swam the day away, I was brought back to the lazy, dock-jumping summers of my childhood. When I almost stepped on a rattlesnake and heard him threateningly shake his tail, I felt a bone-deep, visceral fear course through me.
And the people I’ve met…well, I think that’s the true reason everyone loves this trail.
I met a mother and her twin four-year-olds who had also been hiking since Springer Mountain. When I first heard about Mother Bear, I thought maybe she was forcing Strong Man (the little boy) and Little Butt (his sister) to hike, but then I heard those kids laughing and shouting and playing for an entire mile before I caught them. They were having the time of their lives. And they were good hikers too! Mother Bear told me they averaged 10-15 miles a day. That was better than many adult thru-hikers I’ve met!
I met a couple and their daughter who took me in with only an afternoon’s notice, simply because my dad’s cousin was their friend. Talk about a distant connection! Julie, the daughter, probably drove an hour out of her way to pick me up and then took me to Roanoke to stay the night with her parents, Sam and Sara. The house in Roanoke was amazing—a beautiful garden full of flowers, rooms full of interesting art, and a fully furnished basement with princess-worthy beds, a washer and dryer, a bathroom, and even a TV!
Sara and Sam treated me like family from the moment I stepped through their door. Sara fed me a delicious dinner and breakfast. She made me feel doted upon. Sam and I talked about the trail’s history and his own hiking experience. Their scarily intelligent mini-Australian Shepherd, Twig, kept us all entertained with his constant antics, such as burying his bones under the couch cushions. I swear he understood every word we said to each other. The way his bright blue eyes lit up and the way he cocked his head when Sara would say certain names convinced me of this.
When Sara drove me back to the trail the next morning, I was sad to leave them. But I felt lucky that I had gotten to know them and spend even that short amount of time with them.
These are just a couple of the people I’ve met out here, but that’s what so magical about the trail. There are always more people to meet. It’s been amazing to meet so many different people who all have such interesting stories to tell.
Just to list a few more: Hiker Mom, who also took me in on short notice, let me stay in her furnished basement at no cost and then dropped off water jugs for me along sections of trail that she knew would be dry. Birdman, who would stop to take photos at least every mile and could spend an hour chewing a single bite of food. Driftwood, who looks fifty but is actually seventy, and lives down in the Keys for the winter and then travels the world during the summer. Tom, who despite a heartattack, has run marathons, an Ironman, biked across the country, and plans to snowboard in Antarctica after thru-hiking the AT. Catchup, who could just as easily be named for the condiment and wouldn’t look out of place in a Weasley family photo, has an easy openness to him that is refreshing. Mitch, who was so smart and well-read, that I could hike for hours just listening to him talk and prompting him with the occasional question.
I’ve hiked big mile days, I’ve hiked shorter days. Some days, the miles come easily and freely. Other days, every step is heavy.
I don’t know if I’ve expressed it well, but basically, what I’m trying to say is that despite the fact that trail life is sometimes boring, it is still very much worth doing. There’s real value in it for me.
That’s it for now, I guess. I’ll continue making my long, long way through Virginia. By the way, if anyone ever tells you that Virginia is flat, you send them to me and I’ll make them hike up Bald Knob and down the Priest and back up Three Ridges and then we’ll talk.
Although she does have some nice, relatively level ridge walks, Virginia ain’t no slouch. She’s got 2,000 and 3,000 foot climbs that come out of nowhere. And she makes you do them in weather so humid that your dripping sweat never dries, with no water sources for 10+ miles, in the beating sun. So if anyone ever tries to tell you Virginia’s easy, you send them to me. I’ll set them straight.
Tomorrow, I head into the Shenandoah National Park, apparently land of the bears. And hopefully soon I’ll be making my way out of Virginia, through West Virginia, Maryland and part of Pennsylvania up to that fabled half-way point. Here we go.

