---
title: "Part 1 (days 1-4) Georgia"
output:
  html_document:
    toc: true
    toc_float: true
---

## Part 1 (days 1-4) Georgia

Originally posted on June 4th, 2014 8:11pm

Wow. It has been a crazy 4 days. Here’s an overview:

Day 1: Amicalola Falls State Park Approach trail (8.8 miles); Springer Mtn. —> Justus Creek (14.3 miles on AT, from now on all mileage listed is on the AT)
Day 2: Justus Creek —> Neel Gap (17.4 miles)
Day 3: Neel Gap —> Blue Mtn. Shelter (18.8 miles)
Day 4: Blue Mtn. Shelter —> Dicks Creek Gap (19.1 miles)

Total Mileage: 69.6 miles from Springer Mtn. + 8.8 mile Approach Trail (78.4 miles total)

Right now I’m in a hostel down the road from Dicks Creek Gap called Top of Georgia. It’s an awesome place (brand new this year), and although I’m glad to be here, the extra half mile road walk I did to get here almost put me flat on my back. I am beat. But happy. For the most part. 

As with most adventures, we don’t do them because they’re easy. We do them because they test us. And I’m still in the adjustment period where I’m figuring out my physical and mental limits. I’ve certainly pushed them so far. And there’s been a toll on my body. My knees creak and ache on every downhill. My shoulders are rubbed raw where my pack sits. Every night I go to sleep feeling like there’s no possible way I could walk even one more step.

But the human body is an amazing thing. And every morning, after a mile or two warm up, I get a spring back in my step and I attack the day.

It’s been beautiful. I know the pictures I post can’t possibly do it justice, but I hope they give you an idea of what it’s like out here.

I’m tired, so for now all I’ll post is a snippet of something I wrote my first day on the trail.

Day One

After traveling for almost 20 hours, I finally reached the Hiker Hostel in Dahlonega, GA. The host, an awesome lady who’s hiked the Pacific Crest Trail and the Colorado Trail, showed me the four bunk room I’d be staying in. I snagged a top bunk and immediately crashed. 

After one of the best naps I’ve ever had, I puttered around the hostel. I met a girl named Emily, who was staying at the hostel with her parents while her dad trained for a bike race. I also met a group of five guys: Craig, Ben, Alex, Eric, and Brett. Their plan was to hike to Damascus, VA. They had actually been on the trail for two days already, but Brett had gotten sick. They had to get off at Woody Gap (~20 miles in) to take him to the hospital. They were staying at the hostel to let him recuperate. They were hoping to get back on the trail within a day or two.

After a full night’s sleep, I was finally starting to get pumped for the trail. I had been planning and prepping and daydreaming during biophysics (sorry mom and dad) for months. The moment was here. It was hike time.

The other host drove me to Amicalola Falls State Park (AFSP) so I could take the 8.8 mile approach trail to Springer Mountain and the start of the AT. We had an amazing conversation about his AT thru-hike and the life-changing experience I was about to have. How the trail is all about the journey, not the destination. How I was going to meet so many amazing people. How I should always hike my own hike.

I registered as a thru-hiker (#1357 this year!) and weighed my pack (21 lbs, which seems fitting as that’s the same as my age). The guy who drove me over took my picture under the AFSP arch, the classic pre-AT photo.

I set off with some serious spring in my step. I’m sure I looked silly walking around with a dopey grin on my face. I hiked up the approach trail, starting with a butt burning 600 stairs to reach the top of the falls that give the park its name. They are the tallest falls east of the Mississippi, so it was definitely worth the walk.

The trail flattened out some, but climbed pretty steadily until I reached Springer Mountain. I realized I had already lost my sunglasses. I took it in stride; the trail was just keeping me honest, teaching me a lesson with something I could afford to lose.

I was cruising along the trail. I felt like I was flying. I passed my first white blaze (the marker that will guide me all the way to Maine) and smiled like an idiot. I never wanted to stop. It was everything I had hoped!

They call them mountains out here, but they felt like glorified hills to me. Although the trail was rockier and studded by more tree roots than I’m accustomed to, the trail was gentle, climbing and falling without switchbacks.

I passed a shelter and decided to keep going. I reached another and was tired enough that I stopped and made dinner there. I was going to stay the night, but felt too overwhelmed by all the large group of boys and their fathers. So I pressed on.

On my way, I met an elderly man who goes by the trail name Statesman. He’s going to finish his section hike tomorrow after spending 14 years hiking one state per year. That kind of dedication is incredibly impressive.

I also met three guys named Tugboat, Spider-man and Anchor. They were carrying crazy heavy packs (70lbs!!) but were still making 8 miles per day! They were nice and seemed amazed that I was attempting a thru-hike. They were also chatting with a guy named Viceroy from Minneapolis. He’s about my age and also trying to thru-hike. We set off together to try and reach the next shelter before dark.

We made alright time, but it was clear we were both very tired. Viceroy stopped a bit before me, because I wanted to camp somewhere with a water source. I kept going until Justus Creek. There was a nice retired man camped there named John. He was hoping to make it to the North Carolina border.

I went down to the creek and soaked my feet. I was happy and pleasantly exhausted. It was a good first day.

“A journey of a thousand miles begins with a single step.” Laozi

Oh, also, from the wisdom of Hallie on Days 2-4, Georgia takes it badly when you call her mountains weak. She’s been punishing me with switchbacks, long stretches of piled rocks masquerading as a trail, rock staircases and other ankle-twisting nastiness. Fun times, especially at the end of the day! Check out the pictures to see what I mean. 

Other side note, Brett of the hostel boys went home sick. Unfortunately, Ben also had to head home because of illness. But the other three are still going and are at the hostel too. Hopefully I’ll get to see them more on the trail!

Final last side note, there’s two bunk rooms in the hostel, and I swear two of the guys are having a “snore-off”.

