---
title: "Part 3: Day 9 and 10"
output:
  html_document:
    toc: true
    toc_float: true
---

## Part 3: Day 9 and 10

Originally posted on June 10th, 2014 1:49pm

Day 9: NOC –> Brown Gap Shelter (16 miles)
Day 10: Brown Gap Shelter –> Fontana Village Resort –> Fontana Dam Shelter (12.7 miles)

Miles from Springer: 165.8

Just a quick post because it’s hardly been anytime since my last one! 

Nothing too exciting has happened. The hike out of the NOC wasn’t nearly as hard as I’d been told, but maybe that’s just because I’d take an uphill over a downhill any day. I had planned on stopping at a shelter around 7 miles from the NOC, but I was feeling good after a great night sleep in the hostel, so I just ate lunch there instead. While there I chatted with a father and daughter pair who we’re hiking southbound from Fontana Dam to the NOC. They gave me good info about the upcoming section of trail. Just as I was eating, an older man who goes by Mr. Wonderful hiked down to the shelter.

I had originally met Mr. Wonderful, who looks like a hiking Santa Claus, while resupplying at the NOC. When I told him I didn’t have a trail name yet, he took it upon himself to come up with one. When I passed him on my way out of the NOC, he stopped me and told me my new name. He said it should be Sassafrass Tea because I have some red in my hair and I “look like a sassy girl”. I’m not sure if I’ll keep that one, but it’s funny that the day after writing about trail names I got a suggestion for one.

After lunch, I pressed on. It was only around 2pm, so I was feeling good about the 9 miles I had left before the next shelter. It’s not critical that I stay at a shelter, but after that thunderstorm a couple of days ago, I didn’t want to be caught without a place to hide. And the clouds overhead were dark and threatening and wind was whipping through the trees like it seems to do the day before a nighttime storm.

There was a great view from Cheoah Bald. I took some more vista pictures and took a moment to enjoy the fruit of my climb out of the NOC.

My knees were talking at me as I descended to Stecoah Gap, but thankfully that’s where I experienced my first bit of trail magic! Some kind person who had thru-hiked in 2013 had left a 6-pack of Yoo-hoos and two bags of salt and vinegar chips. I cracked open my first Yoo-hoo (a chocolate milk type drink) and drank it with gusto. I left the huge bags of chips for a bigger group.

It was good that I had fuel because the last 2 miles of the day climbed ridiculously steeply. I wish pictures could do it justice, but you’ll just have to take my word for it that North Carolina does not use nearly as many switchbacks as she should to get you up a mountain. Instead, she has you just climb straight up the sucker.

But I made it and was surprised when I was greeted by a group of six people at the shelter. That was the most people I’ve seen at one shelter. They were all a bit older, mostly 50+. 

There was a pair of brothers there, one of which was a joker who tried to convince me that “Guano” would be a good trail name because it was “Cherokee for robin”. The group had a laugh as I tried to diplomatically side step getting saddled with birdshit as a trail name. Coyote, the joker’s trail name, told me he played that prank on an old girlfriend of his and that she didn’t know what it meant. She went 110 miles proudly telling people her new trail name. She probably would have kept it forever if it hadn’t have been for her mom breaking the bad news about its real meaning.

I also met a couple and two ex-military people who didn’t know each other before the trail but had been hiking together since Winding Stair. The ex-military hiking pair consisted of Hope and her dog Nicky (so cute) and Monk, who is trying to make it all the way to Maine. Monk is a very interesting guy. He talked to the brothers for most of the night about his work with the Navy and the state of the world today. He also told me he’s going to write a book about the AT and that I should too. He thinks it’s a wise financial choice, because the movie based on Bill Bryson’s “A Walk in the Woods” is being filmed right now, so there’s going to be a serious increase in demand for AT related materials after it comes out. I don’t know about writing a book myself, but I’m happy he’s going for it!

I set up in the shelter, but didn’t sleep too well at first. I was happy I did though, because around 3:20am, the wind and rain started pounding the shelter so hard that it sounded, as Hope put it the next morning, like someone was throwing buckets of water at us, buckets included. Then, the thunder picked up and there were some lightning flashes. It was nothing like a couple days ago, but it was very loud in the metal roofed shelter. At one point, it devolved into just a dull roar, like a jet was parked outside. But thankfully it blew itself out pretty quickly and the storm died down around 4am.

This morning I woke up early, mostly because everyone else was already up. I was out hiking by 7:30am. I planned to make it to Fontana Dam Shelter, which is known as the “Fontana Hilton” because it has hot showers. Oh boy.

I find that when I’m planning on reaching something exciting like that at the end of the day I get completely fixated on it. I can’t just relax and let the miles come to me. Instead, I’m constantly thinking about how awesome it will be when I get where I’m going. And let me tell you, that makes the day move by like molasses. Every mile took forever. It didn’t help that the last section was a long couple of miles of downhill. My knees weren’t having it. I won’t write what I was saying, but let’s just say it wasn’t pretty. A lot of cursing and tirades against the trail’s family and ancestors and children…you get the picture.

But then I came across a turtle. Well, it’s more accurate to say I almost stepped on a turtle. 

I shocked him almost as much as he shocked me. He made this little whistle-whooshing noise like he couldn’t believe that his extraordinarily long life had almost been ended by this upstart whippersnapper’s foot. Such an indignity. But all joking aside, it was pretty amazing. He instantly sucked all his limbs and tail into his shell. Just the top of his nose stuck out of his shell. I took some pictures and then waited to see if he would start walking again. I learned to never enter a standoff with a turtle, because he will always win. I left him to his day and went onwards with mine, cursing all the way down to the Fontana Dam Marina.

At the Marina I washed up and got a shuttle into the Fontana Village Resort. I’d been dying to do laundry, but was unsure how to wash all of my clothes when I had nothing to change into. Luckily, the lady at the general store is amazing and thought ahead for all of us hikers. She has scrubs on hand for hikers to wear while doing laundry. I could’ve hugged her. She made my day.

And basically all I’ve been doing since I got in around 1pm is hanging out, doing laundry, and eating. A much needed relaxation half-day after putting a lot of strain on my body. Tomorrow I make the huge climb into the Smokies. I need to be well rested for that. Maybe I’ll finally see a bear on this trip. Apparently the Smokies are known for their huge black bear population. We’ll see!

