---
title: "The Rest"
output:
  html_document:
    toc: true
    toc_float: true
---

## The Rest

Originally posted on September 26th, 2014 7:00pm

On September 9th, I stood on top of Katahdin and got sunburned.  I had views for miles. I could see lakes I had walked by and small mountain ranges I had climbed. I was on top of the world.

It had taken me 101 days to get there, from a first day standing under the archway that marked the Approach Trail, from a first day standing on Springer Mountain, from a first day doubting if I could make it, if my body could take it.

I had finished. I was done.

But all of my plans ended there.

What now?

~~

So what’s the story between Virginia and Maine? How did I go from being kind of bummed out about hiking all day to feeling unsatisfied unless I had hiked all day?

You know, I’m not totally sure. Maybe it has to do that in Virginia, I was catching a lot of thru-hikers that seemed like they weren’t super into the whole hiking thing. They were spending more and more time in town and less time on trail. They had started months before me. And we were in the same place.

I would avoid telling them my start date at all costs. Unfortunately, most trail conversations follow this line of questioning:

Where ya comin’ from? Where ya headin’ to? When’d ya start?

When that last question came up, I would reluctantly spit out June 1st . Their expressions would instantly change as they did the math.

Some people were happy for me, especially when I told them I was having a good time walking all day.

Some people were not as positive about it. I think I made a lot of them feel defensive about their hike or insecure about whether or not they could finish (or if they even wanted to finish). So then our happy conversation about trail life would turn into a grill session.

How many miles do you do a day?! You must be doing 30s everyday! Are you running?! Have you even seen anything?! You couldn’t possibly.

They made me feel guilty about liking to walk all day and that I wasn’t doing the trail the right way. That I was missing out on something vital.

And from their point of view, maybe I really was.

Because of my pace, I hadn’t hiked for hundreds (or even thousands!) of miles with one tightly knit group of people. I hadn’t taken weeks worth of zeroes to explore the culture of the little towns we passed. I hadn’t gotten off trail for a couple days to do work-for-stay on an organic farm.

Most of the people that I met came for more than just hiking. They came for a journey. I had initially thought that maybe that was what I was going to the AT for, but I was also finding that mostly I just wanted to hike. I wasn’t sure what I wanted, and if I needed to change the type of trip I was on. I felt like I was being drawn in two different directions. I think that’s where I was at mentally in Virginia.

Then, a guy named Dude caught me. He started on June 9th, and he was trying to hike the AT in 90 days. To meet that kind of goal, he had to hike all day and seemed to really like doing it.

Suddenly, I wasn’t the only crazy one when we caught up with other thru-hikers. I had company. I hiked with him and CatchUp through Shenandoah National Park. Then CatchUp took a zero, so I hiked with Dude to Harpers Ferry, WV.

During that time hiking with both of them, I realized that yeah, I really did want to hike. All the time.

All of those other things sounded like fun to me, but at the same time, I had come to hike the AT. So I wanted to hike the AT. I just wasn’t as interested in doing other things when I could keep hiking and see whatever was around the next bend. I was just on a different kind of trip than a lot of the people I met, and that was okay.

Then I took the train from Harper’s Ferry, the mental halfway point of the trail, into Washington D.C. and hung out with my friend, Kiren, for four days. Although I had a great time seeing him and was so happy to be there, I felt this compulsion to get back and get hiking.

After the simple life of the trail, D.C. was a bit much. Everything and everyone seemed to be in such a rush. I felt very out of place and overwhelmed by all of the loud, speeding cars and the perfectly dressed people on the street who didn’t even look at each other.

When I got back to Harpers Ferry, I ran into CatchUp one more time before I hiked out. We caught up and I heard that he had seen Mitch. It was great to hear that he was still hiking.

Then, I took off. I felt like I was flying down the trail. I walked all day and it was awesome. I felt resolved. I liked this. Even when it was hard and brutal, at the end of the day I was so incredibly satisfied. I felt strong and happy. I was doing what was right for me.

~~

I came to the conclusion that the mileage of each day didn’t matter. I stopped keeping track of it. Instead, on a day-to-day basis, I would pick out a couple places that I thought I could end up at depending on how I felt, I would hike until it was getting dark, and then I would stay at whichever one was closest.

Some days, I hiked farther than others. Some days, I felt like chilling, so I’d plop down on a rock to nap or soak my feet in a stream. The numbers weren’t important. I was heading north, that’s all that mattered.

So instead of listing my daily mileage and where I stayed each night, I think I’ll just finish this thing off with a few stories from the states I went through in the second half of my trip.

~~

Maryland flashed by and before I knew it, I was crossing the Mason-Dixon line into Pennsylvania. Not 40 miles later, I hit the actual halfway point of the trail and I was finally closer to Maine than Georgia.

To celebrate, thru-hikers eat a half-gallon of ice cream to complete the Half-Gallon Challenge at Pine Grove Furnace State Park. It was surprisingly easy. Both Grubnugget (whose trailname made my dad laugh and say once again that I had gotten pretty lucky with my own) and I finished in less than 40 minutes…and ordered more food afterwards. The hunger was starting to get unreal.

Pennsylvania is also where I stopped using trekking poles. One pole tripped me up on some rocks, resulting in a pole bent at a 90° angle and a bloody knee. When I tried to bend the pole back, it snapped in half. That decided it. No more poles for me.

I also got to see my Uncle Ken in Pennsylvania. We went to a movie and he fed me lots of food, including tons of fruit. It was nice to catch up with him and take a much needed shower.

From the time I left Pennsylvania, the states seemed to fly by.

Almost every hiker I talked to had the same opinion on New Jersey: it was surprisingly awesome. I think everyone had pretty low expectations, but Jersey had it all. Nice ridge-walking, views, rattlesnakes, copperheads, bears, fewer rocks than the last section of Pennsylvania, and delis everywhere. I hardly had to walk off trail to get myself a sandwich or pizza.

New York wasn’t my favorite state. A lot of the trail seemed to be routed up and over huge boulders for no apparent reason. It also ran across so many roads it was ridiculous (I’m talking four lane highways!). But there was one shelter that was perched on top of mountain and at night, I could see the NYC skyline lit up in the distance. That was pretty sweet.

Connecticut and Massachusetts were both gone in the blink of an eye. Connecticut was a lot of walking by rivers. And gnats. Lots of gnats. Gnats that liked to fly into my eyes and open mouth. Mosquitoes and rain dominate my memories of Mass. On one hot humid day, I must’ve looked like I was dancing down the trail with the way I was slapping myself to kill mosquitoes. I was getting one or more every time I hit myself. I picked up the pace and practically ran through that boggy, lowland section of trail.

People were also talking non-stop about the huge weather that was headed our way the next day. Most people decided to take a zero, just to avoid it.

And what a day it was. When I got up, it was just sprinkling so I decided to go for it and hike. It started pouring about 15 minutes later. Then the wind started. And the thunder. I gave up on keeping my feet dry after a couple miles and just waded straight through the muddy river that the trail became. Bog boards, which are laid down to help hikers avoid the muddiest sections, were completely submerged. Streams that had been calmly trickling the day before, raged and overflowed their banks.

It could’ve been miserable. And it was, for a while. Then in the late afternoon, the rain stopped and the sun came out. By the time I finished for the day, I was completely dry except for my feet. It was kind of fun to be one of the only people out hiking that day. Also, at the shelter I stayed at for the night, I got to see two people I hadn’t seen since just outside the Smokies. That in itself made the whole day worth it.

Although it’s commonly referred to as VerMud by many AT hikers, I was lucky enough to have great weather all through Vermont. It felt like home in a lot of ways. Blue skies, sun, great views, just chilly enough to be comfortable, thick moss, lots of water, pine needles piled so thick on the trail it was like cloud walking. And incredibly kind people. I saw more trail magic in Vermont than any other state, from sodas left on the side of the road to a family who fed me a full breakfast when I hiked by their house.

New Hampshire was pretty amazing. I started by walking right through Hanover, NH, where Dartmouth College is located. A lot of the local restaurants give thru-hikers free food. I got a donut, a bagel and a slice of pizza, all for free! Awesome.

In northern New Hampshire, the trail goes through the White Mountains, which are known as having some of the hardest hiking on the whole AT. It also has some of the biggest rewards to make you forget all about that. See, in the Whites, they don’t do switchbacks. Instead, they just run the trail straight up the mountain. At times, it was basically bouldering with a huge backpack on. It was fun. But the views were also ridiculous, because we were finally above treeline. I had incredible weather and got sunburned every time I was on a ridge walk.

Then I got into Maine, and oh man. I loved Maine. I was there at a perfect time—no mosquitoes or black flies, not too cold, not too hot, blue skies and crystal clear lakes around every bend. I also saw a moose! After weeks of seeing big piles of moose scat, I turned a corner and there he was, standing right in the middle of the trail. We must’ve stood and just looked at each other for a good five minutes. I won the staring contest, but only because he got bored and wandered off.

Oh yeah. Maine is also where my backpack broke. Here’s how it went down.

I hiked about eight miles to a road and hitched into the small town of Stratton. I resupplied, hung out with some other thru-hikers, ate a pint of ice cream, and got a ride back out of town to keep hiking. It was a beautiful sunny day, and I was thinking about the views I’d get from the Bigelow range. I was also less than a mile from hitting the 2000 mile mark. I was excited to hike.

Then, I slipped off of a bog board. This wasn’t unusual. Those things are permanently slick and I don’t have the greatest balance. So I trip a lot. Not thinking anything of it, I shook it off and started walking again. But something was very wrong. My pack was practically falling off of me.

I slung it off my shoulder to inspect the damage. One strap was hanging on by a thin strip of cuben fiber that had peeled down to the lower half of the pack.

Okay, no worries I thought. I can fix this. This is why I’ve been carrying that duct tape around for thousands of miles.

Except it wasn’t sticky anymore. And neither was the other tape I had. All I wanted to do was keep walking. And I couldn’t. Or could I?

For about 30 seconds, I almost had myself convinced that I could continue walking and just carry that janky, one-strap pack all the way to Katahadin. It wouldn’t be a big deal. Right?

I told my crazy brain to stop with the stupid. I swore a lot. Then I turned around and hiked the two miles back to the road.

I sat dejectedly on the side of the road for a while before deciding that I should probably grow up and hitch back into town. I sighed, slapped on my best smile and stuck my thumb out.

Luckily, only a few cars passed before a middle-aged guy in a truck pulled over. He hopped out to open the back for me. I mentioned in passing that I was hiking the AT and my pack had broken.

Instantly, he started thinking out loud about what I could do. He was from Stratton, and he knew a bunch of people in town.

“Actually, I’m looking after the Laundromat for a friend,” he said. “I think someone left a pack there. I’ll grab it for you!”

I smiled and said he didn’t have to do that, but he insisted. I really didn’t think anything would come of it, but I felt grateful that he was so willing to help me.

I told him I was from Washington State and then asked him if he had ever been out there.

“Yeah! I actually backpacked part of the Olympic coast, in the ‘80s.”

That made me really happy. I had done that same trip with my friends in high school. We talked about how great the hiking in Washington is right up until he dropped me back at the hostel in town. As he pulled away, he rolled down the window and yelled that he’d be back with whatever he could find at the Laundromat. I thanked him and waved as he drove away.

Some thru-hikers I knew were sitting outside of the town’s tiny grocery store, so I went over and watched them eat. They were a funny group and got me laughing with their antics. One guy came out of the store with an entire watermelon, cut it in half, got his spoon out and proceeded to eat the whole thing.

“He does that in every town,” his friend said, shaking his head.

The best part was that the kid’s name was Apple. He must’ve really liked fruit.

About twenty minutes later, the truck pulled back up. I walked over and the man pulled a pack out.

“I’m not sure if this will work, but this is what was at the Laundromat.”

It was a Spiderman backpack.

It was too small. The way the man held it out, I could tell he had been disappointed by the size of it too. I smiled and started to shake my head. “I don’t think so, but thank you for going to the trouble.” But then he pulled another pack out.

“What about this one?”

It was big pack, navy with a bright red bottom compartment. I turned it around a couple times. It was definitely made for someone taller than me, but I could make it work. It could work!

“Yeah, I think so!” I smiled excitedly at him.

“Great! Well, you know that trip I was telling you about? This is the pack I took on it.”

Instantly, I felt guilty. “I can’t take your pack! This is too much.” I tried to hand it back to him.

He refused and told me to take it. Then he reached back into the truck, grabbed a piece of paper and jotted down his address.

“Send me a postcard when you finish. Good luck on your hike!” He gave me a hug and drove away. I could’ve cried, I was so thankful.

I walked back over to the thru-hikers, told them what happened, and they all just grinned, saying knowingly, “The trail provides.”

Isn’t that the truth? If Jeff hadn’t been so generous, I likely would’ve had to wait in Stratton for a couple more days at least. I would’ve had to buy and ship a new pack to myself or I would’ve had to figure out a way to hitch to a bigger town with an outfitter. Instead, I got to hike out the next day. People are amazing.

The pack was a little bit outdated. It had a Velcro hipbelt. It didn’t have any pockets you could reach while wearing the pack, so any time I wanted to get some water, I’d have to take the sucker off and dig the bottles out. It took some time to get used to it, especially the difference in weight. My old pack weighed about a pound. The new pack was about 5 lbs. That might not sound like a big difference, but I felt it. (As a side note, my pack wasn’t as light as it was at the beginning of my hike either. I’d started carrying more food and water, so with my old pack, I was usually carrying around 30 lbs.)

But it carried my stuff. That was all that mattered. It did its job. It got me to Katahdin.

All thru-hikers have to sign in with a ranger before they can hike the five miles up Katahdin. I found out that I was the 447th northbounder to finish in 2014. A lot of hikers will leave their packs with the ranger and borrow a daypack for Big K, but I felt like my pack deserved to finish with me.

The weather was perfect. Blue skies, cool but not cold. I smiled the whole way up the mountain. It was one of the hardest climbs I did. Hand-over-hand climbing, rebar anchored into the rock to help hikers over the trickiest sections, lots of elevation gain, and some of the best views I had the entire trip. It was a great mountain to end on. It made me work for it.

When I saw the sign that marked the summit, I couldn’t help but pick up my pace. My breathing sped up. I wanted to be there. Now.

My eyes were fixated on it. I took the final steps. I reached out and touched it. Words fell unnoticed from my lips.

“Holyshitholyshitholyshitholyshit.”

I teared up a little bit and smiled so wide I felt like my face would split. I couldn’t believe I was actually there. I was done. I was on Katahdin. Holy shit.

There were some other thru-hikers hanging out nearby, Achilles, AB and Zeus. They took my picture and shared the moment with me. I noticed all of the day hikers around me for the first time. I was suddenly so thankful there were other thru-hikers around who understood what this day meant.

I sat down on a rock and pulled out some food and water. I hadn’t stopped to eat or drink once I had started the final five-mile ascent. I couldn’t bring myself to. But now I was done. All of my plans had ended here. I hadn’t thought of what I was going to do once I reached the summit. I hadn’t thought about which trail I was going to take down from the summit, let alone how I was going to get home. I hadn’t thought about anything beyond the trail in so long. I didn’t know if I still knew how. Oh well, I thought, it’ll all work out. Everything has so far!

I got to talking to the other thru-hikers, feeling like we were friends already even though we had met only minutes before. They were going to hike the Knife’s Edge down Katahdin. It is said to be equal parts awesome and terrifying. They were nice enough to invite me along. I eagerly agreed.

I happily hiked along with the guys, chatting and feeling a crazy happiness wash over me in waves every couple minutes. I was tired, in a way I hadn’t been on the rest of my hike. It was like my body knew we were done and it finally decided to inform me that my feet hurt and my knees and my arms and everything. I didn’t care though. I was having a great time.

We got to the bottom of the mountain and the guys were going to hitch into a nearby town Millinocket. However, Baxter State Park, where Katahdin is located, is pretty remote, so it would be a long hitch. Luckily, most people who were leaving the park had to drive through Millinocket so we figured we had a good chance of getting a ride.

We walked around and asked a few people before a very nice Dutch couple agreed to drive us, even though I’m sure we smelled to high heaven. They were actually staying in Millinocket, at the hostel we were going to stay at. We couldn’t have gotten a better hitch!

We got checked into the hostel and then walked into town to find some celebratory food. We went to the Appalachian Trail Café where we learned about something called the Summit Sundae.

There were two thru-hikers already sitting at a table. One looked absolutely miserable. He was sitting with elbows on the table, his head cradled in his hands, and a large plastic bowl in front of him. The other looked downright gleeful. He playfully pushed the bowl towards his friend.

“Come on man, you gonna finish this or not?”

The other guy groaned. The happy friend was wearing a white shirt with the words “I conquered the Summit Sundae” written above a picture of a towering sundae. I wanted that shirt. I wanted to look that miserable.

The Summit Sundae is not your average eating challenge. The half-gallon challenge seems like child’s play in comparison. Here’s the description of the sundae from its Facebook page (yes, it has an entire Facebook page dedicated to it): “starting with a banana, then 14 scoops of ice cream (one for each state the AT crosses), Snickers candy bar (hikers’ favorite food), a handful of M&M’s and an AT Cafe’s famous doughnut (made famous in Washington DC) all that topped with chocolate syrup, whipped cream & cherries. Eat it by yourself and you get to add your name to the pole of fame and we’ll give you a T-shirt & a bumper sticker and you get to keep the bowl!!”

It comes out to about 4.5 POUNDS of food.

If there was ever a time when I could put that much food away, it was on that day. Achilles and I joked with each other  about it. We were having such an amazing day! We needed to feel the full range of human emotions to make it complete. We were feeling entirely too successful. We needed to hate ourselves a little bit too.

So, as Zeus and AB shook their heads at us and ordered real food, Achilles and I mentally prepared for our last challenge. The one thing we had failed to consider was the fact that the restaurant would be closing in about an hour. The sad looking kid had been working on his sundae for the better part of two hours already. We had a serious time disadvantage.

We decided to try and outrace the full feeling and trick our bodies into putting the whole sundae away. We only had to keep it down for five minutes after it was all eaten.

When the sundaes came out, several groups of tourists came over and took our pictures. Then we got to it. I started by searching out the “special bits” that they’d added. The donut (think dense cake, not Krispy Kreme), snickers bar (frozen to a tooth-shattering degree), and banana were all cut up and scattered amongst the chocolate, strawberry and vanilla ice cream scoops.

“This is awesome!” I said, smiling wide as I shoveled ice cream into my mouth. “Right now this feels like a great decision. I know that pretty soon I’m not gonna feel good, but I’m super happy right now!”

But all too soon, I started getting cold. This was one of the problems the successful Summit Sundae-er had warned us about. That much ice cream in your stomach will drop your core temperature really quickly. His buddy was wearing multiple jackets. Achilles and I were not. Pretty soon, I was shivering so much I could hardly get the spoon to my mouth.

Then I hit a wall. All I had left was a thin layer of ice cream soup. I started thinking about having to drink that. That sounded like the worst. I sat there and stared at for a while. All of a sudden, I knew. I had to get to the bathroom.

Did you know ice cream is still cold coming back up?

It really wasn’t even gross, and I felt so much better, I wasn’t even too disappointed about not getting that shirt. Achilles ended up getting way closer to finishing than I did. He started drinking his ice cream soup like a champ, but with barely one sip left, he also had to make a trip to the restroom.

The guy behind us ended up finishing his sundae and getting the shirt. I was happy for him and just a tad jealous. We made for good entertainment for the tourists though!

The next morning, Zeus, Achilles and AB were getting on a bus that went to Bangor, ME to rent a car. I learned that the bus also went all the way to Boston, Mass. I got on the bus with them. While I was on the bus, I found a flight from Boston to Seattle that left that evening. So, I ended up getting home the day after I finished my hike.

Everything worked out.

~~

So that’s it. To everyone that read this thing, I’m sorry that I left you hanging for so long. I really do appreciate everyone’s interest in my hike. The support of family, friends, and strangers I met along the way was invaluable. Thank you for coming along for the ride.
It was the most consistently happy I’ve ever been.

Sonic

